# Generated by Django 3.2.6 on 2021-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deci_number',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
