# Generated by Django 3.2.6 on 2021-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20210909_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Employee', 'Employee')], max_length=100, null=True),
        ),
    ]
