# Generated by Django 3.2.6 on 2021-09-10 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_profile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo_list.profile'),
        ),
    ]
