# Generated by Django 3.2.6 on 2021-09-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_contact_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.profile'),
        ),
    ]
