# Generated by Django 3.2.6 on 2021-09-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_alter_contact_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='prof_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo_list.profile'),
        ),
    ]
