# Generated by Django 3.2.6 on 2021-09-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_alter_contact_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='profile_id',
            new_name='prof_id',
        ),
    ]
